name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "53215110-59a17126-ae9a-4f4c-9a1e-7a4dbc7868ed" -e "53215110-3871373b-936f-49ed-9a89-ea88b40fb2c6"
